inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/master/style/ruby/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "tmp/**/*"
    - "gemfiles/*"

Style/EmptyMethod:
  EnforcedStyle: expanded
