  Feature:
    As a user of Rails3 and factory_girl
    I would like to use factory_girl_rails generators and specify a suffix on the files that are generated.
    So that I can more easily locate any and all files generated by factories.

  Background:
    Given I successfully run `bundle exec rails new testapp`
    And I cd to "testapp"
    And I add "factory_girl_rails" from this project as a dependency

  Scenario: The factory_girl_rails generators using custom suffix and Rspec gem ????????????????
    When I run `bundle install` with a clean environment
    And I add "rspec-rails" as a dependency
    Then I set the FactoryGirl :suffix option to "factory"
    And I run `bundle exec rails generate model User name:string --fixture-replacement=factory_girl` with a clean environment
    And I run `bundle exec rails generate model Namespaced::User name:string --fixture-replacement=factory_girl` with a clean environment
    Then the output should contain "spec/factories/users_factory.rb"
    And the output should contain "spec/factories/namespaced_users_factory.rb"
    And the file "spec/factories/users_factory.rb" should contain "factory :user do"
    And the file "spec/factories/namespaced_users_factory.rb" should contain "factory :namespaced_user, :class => 'Namespaced::User' do"

  Scenario: Using Factory Girl and Factory Girl Rails with Test Unit generates a factory file and does not generate a fixture file
    And I run `bundle install` with a clean environment
    Then I set the FactoryGirl :suffix option to "factory"
    And I run `bundle exec rails generate model User name:string --fixture-replacement=factory_girl` with a clean environment
    Then the following files should exist:
      | test/factories/users_factory.rb |
    And the following files should not exist:
      | test/fixtures/users_factory.yml |

  Scenario: Using Factory Girl and Factory Girl Rails with RSpec should generate a factory file
    When I add "rspec-rails" as a dependency
    And I run `bundle install` with a clean environment
    Then the output should contain "rspec-rails"
    Then I set the FactoryGirl :suffix option to "factory"
    And I run `bundle exec rails generate model User name:string --fixture-replacement=factory_girl` with a clean environment
    Then the following files should exist:
      | spec/factories/users_factory.rb |
    And the following files should not exist:
      | spec/fixtures/users_factory.yml |

